name: test script
on:
  workflow_dispatch:
  #schedule:
    #- cron: "15 0 * * *"
    
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  Check-Dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v3
      - name: setup gh extension
        run: gh extension install andyfeller/gh-dependency-report
      - name: run report
        run: gh dependency-report github gh-gei -o test.csv  
      - name: upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: test.csv
      #- name: Run GO Script
       # run: go run main.go github gh-gei #-o test.csv
      #- name: Hello World
        #run: python hello_world.py
        #shell: sh
